// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACquSYARFFytNzPr9e8QF16LlCprnQm5A',
    appId: '1:891785324634:web:38f44d9880e71f46965063',
    messagingSenderId: '891785324634',
    projectId: 'messenger-1341c',
    authDomain: 'messenger-1341c.firebaseapp.com',
    storageBucket: 'messenger-1341c.firebasestorage.app',
    measurementId: 'G-KM3R5HVXR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTMt-tNWt65odGthFXO7eQzyfDe_1uW8k',
    appId: '1:891785324634:android:8ad1c56ea19ac7d9965063',
    messagingSenderId: '891785324634',
    projectId: 'messenger-1341c',
    storageBucket: 'messenger-1341c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKimeHQcOp4zQxr1eRj4oQfZSUCth-Dzg',
    appId: '1:891785324634:ios:5ebae95e6e9c29ba965063',
    messagingSenderId: '891785324634',
    projectId: 'messenger-1341c',
    storageBucket: 'messenger-1341c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKimeHQcOp4zQxr1eRj4oQfZSUCth-Dzg',
    appId: '1:891785324634:ios:5ebae95e6e9c29ba965063',
    messagingSenderId: '891785324634',
    projectId: 'messenger-1341c',
    storageBucket: 'messenger-1341c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACquSYARFFytNzPr9e8QF16LlCprnQm5A',
    appId: '1:891785324634:web:b9d0ead97df22897965063',
    messagingSenderId: '891785324634',
    projectId: 'messenger-1341c',
    authDomain: 'messenger-1341c.firebaseapp.com',
    storageBucket: 'messenger-1341c.firebasestorage.app',
    measurementId: 'G-14WBLNSLDP',
  );

}